In [1]:
import pandas as pd
import glob
import os

In [2]:
path = os.getcwd()
filenames = glob.glob(os.path.join(path + "/resources", "*.csv"))
  
dfs = []

# loop over the list of csv files
for filename in filenames:

    dfs.append(pd.read_csv(filename, index_col=None, header=0))

# Concatenate all data into one DataFrame

data_2020 = pd.concat(dfs, axis=0, ignore_index=True)
data_2020

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,226,2020-01-01 00:04:50.1920,2020-01-01 00:08:37.0370,3186,Grove St PATH,40.719586,-74.043117,3211,Newark Ave,40.721525,-74.046305,29444,Subscriber,1984,2
1,377,2020-01-01 00:16:01.6700,2020-01-01 00:22:19.0800,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,26305,Subscriber,1989,2
2,288,2020-01-01 00:17:33.8770,2020-01-01 00:22:22.4420,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,29268,Customer,1989,1
3,435,2020-01-01 00:32:05.9020,2020-01-01 00:39:21.0660,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,29278,Customer,1969,0
4,231,2020-01-01 00:46:19.6780,2020-01-01 00:50:11.3440,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,29276,Subscriber,1983,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336797,1750,2020-12-31 23:07:44.0030,2020-12-31 23:36:54.4710,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,40440,Customer,1969,0
336798,1519,2020-12-31 23:18:00.2630,2020-12-31 23:43:19.8590,3184,Paulus Hook,40.714145,-74.033552,3195,Sip Ave,40.730897,-74.063913,46340,Customer,1969,0
336799,1761,2020-12-31 23:31:09.4620,2021-01-01 00:00:31.3290,3195,Sip Ave,40.730897,-74.063913,3270,Jersey & 6th St,40.725289,-74.045572,40907,Customer,1998,1
336800,637,2020-12-31 23:35:45.4640,2020-12-31 23:46:22.7300,3681,Grand St,40.715178,-74.037683,3199,Newport Pkwy,40.728745,-74.032108,42250,Customer,1969,0
336801,1607,2020-12-31 23:48:34.5750,2021-01-01 00:15:22.3090,3267,Morris Canal,40.712419,-74.038526,3267,Morris Canal,40.712419,-74.038526,48742,Subscriber,1982,1

In [3]:
# Checking for NaN values
data_2020.isnull().sum().sum()

0

In [4]:
# Changing encoders for gender (0 = Unknown, 1 = male, 2 = female)
data_2020['gender']= data_2020['gender'].map({0: "Unknown", 1: "Male", 2: "Female"})

In [5]:
# Formatting time columns to pandas datetime format
data_2020["starttime"]= pd.to_datetime(data_2020["starttime"])
data_2020["stoptime"]= pd.to_datetime(data_2020["stoptime"])

In [6]:
# Checking for spelling mistakes in station names
data_2020["start station name"].value_counts()

Grove St PATH                 22930
Newport Pkwy                  19844
Liberty Light Rail            16933
Hamilton Park                 14718
Sip Ave                       13663
Marin Light Rail              13615
Newport PATH                  12855
Harborside                    12757
Columbus Dr at Exchange Pl    12586
JC Medical Center             10795
City Hall                      9715
Morris Canal                   9209
Warren St                      9177
Washington St                  8855
Paulus Hook                    8069
Newark Ave                     7872
Van Vorst Park                 7301
Columbus Drive                 7285
Jersey & 3rd                   6075
McGinley Square                5732
Brunswick St                   5485
Brunswick & 6th                5483
Jersey & 6th St                5388
Manila & 1st                   5346
Lincoln Park                   5339
Grand St                       5165
Baldwin at Montgomery          4865
Dixon Mills                    4726
Monmouth and 6th               4610
Essex Light Rail               4411
Hoboken Ave at Monmouth St     4023
Montgomery St                  3976
Lafayette Park                 3619
Bergen Ave                     3563
Astor Place                    3546
Pershing Field                 3390
Fairmount Ave                  3345
York St                        3328
Hilltop                        3303
Heights Elevator               3155
Journal Square                 2973
Oakland Ave                    2358
Communipaw & Berry Lane        2276
Glenwood Ave                   1960
Riverview Park                 1948
5 Corners Library              1743
Christ Hospital                1632
Union St                       1622
Dey St                         1621
Jackson Square                 1493
Leonard Gordon Park            1123
JCBS Depot                        1
Name: start station name, dtype: int64

In [7]:
data_2020.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,226,2020-01-01 00:04:50.192,2020-01-01 00:08:37.037,3186,Grove St PATH,40.719586,-74.043117,3211,Newark Ave,40.721525,-74.046305,29444,Subscriber,1984,Female
1,377,2020-01-01 00:16:01.670,2020-01-01 00:22:19.080,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,26305,Subscriber,1989,Female
2,288,2020-01-01 00:17:33.877,2020-01-01 00:22:22.442,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,29268,Customer,1989,Male
3,435,2020-01-01 00:32:05.902,2020-01-01 00:39:21.066,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,29278,Customer,1969,Unknown
4,231,2020-01-01 00:46:19.678,2020-01-01 00:50:11.344,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,29276,Subscriber,1983,Female

In [9]:
data_2020.to_csv("resources/2020-citibike-tripdata.csv", index=False)